name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'drag-n-drop-app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Navigate to frontend directory
        run: cd drag-n-drop-app

      - name: Install dependencies
        run: npm install
        working-directory: ./drag-n-drop-app

      - name: Build React app
        run: npm run build
        working-directory: ./drag-n-drop-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./drag-n-drop-app/dist